config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :members, :controllers => { registrations: 'registrations' }
  resources :posts, only: [:new, :create, :index]
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_member!, only: %i[new create]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = current_member.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = current_member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:member).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:member).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
  <body>
  	<% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>
  	<nav class="navbar is-info">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item", style: 'text-decoration:none;' do%>
  			<h1 class="title is-5"><span class="icon"><i class="fas fa-users"></i></span>  Members Only</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
					<span></span>
					<span></span>
					<span></span>
  		</div>
  	 </div>

			<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					<div class="field is-grouped">
            <% if member_signed_in? %>
     			<p class="control">
					<%= link_to 'New Post', new_post_path, class: "button is-info " %>
				</p>
              <p class="control">
                <%= link_to current_member.username, root_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_member_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_member_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_member_registration_path, class: "button is-info" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
      <%= f.input :title, label: "Give your secret a title", input_html: { class: "input is-link "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>

    <%= f.input :body, label: "Write your secret!", input_html: { class: "textarea is-small"}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/posts/_members_blog.html.erb
<% @posts.each do |post| %>
  <div class="box">
  <article class="media">
  <figure class="media-left">
      <p class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/128x128.png">
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
        <strong><%= current_member.name %></strong><br />
        <small><%= current_member.username %></small>
              <%= post.title %><br>
              <%= post.body%>
        </p>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
              <%= link_to posts_path, style: 'text-decoration:none;', class: "level-item" do %>
                <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
              <% end %>
        </div>
        <div class="level-right">
              <small class="level-item"><%= post.updated_at.strftime("Updated: %m-%d-%Y at: %H:%M") %></small>
        <div>
      </nav>
    </div>
    <%= link_to new_post_path, method: :delete, data: { confirm: 'Are you sure?'} do %>
    <div class="media-right">
      <button class="delete"></button>
    </div>            
    <% end %>
    </article>
    </div>
    <%end %>

app/views/posts/_no_members_blog.html.erb
<% @posts.each do |post| %>
<div class="box">
<article class="media">
<figure class="media-left">
    <p class="image is-64x64">
      <img src="https://bulma.io/images/placeholders/128x128.png">
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><strong>Incongnito</strong><br /></strong>
  				<small>@hidden</small><br/>
          <small>Someday</small>
        <br>
            <%= post.title %><br>
            <%= post.body%>
      </p>
    </div>
    <nav class="level is-mobile">
      <div class="level-left">
      </div>
      <div class="level-right">
            <small class="level-item">Someday</small>
      <div>
    </nav>
  </div>
  </article>
  </div>
  <%end%>

app/views/posts/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered mt-3">
      <div class="colum is-half">          
          <h1 class="title is-5">Members Posts</h1>
          <%= simple_form_for(@post) do |f| %>
          <%= f.error_notification %>
          <div class="field">
            <div class="control">
                <%= f.input :title, label: "Give your secret a title", input_html: { class: "input is-link "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>
                <%= f.input :body, label: "Write your secret!", input_html: { class: "textarea is-small"}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>
            </div>
          </div>
          <%= f.button :submit, class: "button is-info" %>
          <%= link_to 'Back', posts_path,  style: 'text-decoration:none;', class: "button is-info" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered mt-3">
      <div class="colum is-half">          
          <h1 class="title is-5">Members Posts</h1>
          <% if member_signed_in?%>
          <%= render 'form'%><br>
          <%= render 'members_blog'%>
          <% else %>
          <%= render 'no_members_blog' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>